const express= require('express')
const { getUserOrders, updateOrderStatus, getAllOrders, placeOrder, cancelOrder, requestReturnOrder, approveReturnRequest, rejectReturnRequest, changeStatus, cancelOrderItem, returnOrderItem, approveItemReturn, rejectItemReturn } = require('../controller/orderController')
const router = express.Router()

router.get('/',getAllOrders)
router.post('/:userId/place-order',placeOrder)
router.get('/:userId',getUserOrders)
router.put('/:orderId/change-status/:status',changeStatus)
router.put('/:orderId/cancel-order',cancelOrder)
router.put('/:orderId/request-return-order',requestReturnOrder)
router.put('/:orderId/approve-return-request',approveReturnRequest)
router.put('/:orderId/reject-return-request',rejectReturnRequest)
router.put('/:orderId/items/:itemId/cancel',cancelOrderItem)
router.put('/:orderId/items/:itemId/return',returnOrderItem)
router.put('/:orderId/items/:itemId/approve-return',approveItemReturn)
router.put('/:orderId/items/:itemId/reject-return',rejectItemReturn)
module.exports=router     