export const SET_REGISTRATION_DATA='SET_REGISTRATION_DATA'
export const REMOVE_REGISTRATION_DATA ='REMOVE_REGISTRATION_DATA'

export const SET_AUTH ='SET_AUTH'
export const REMOVE_AUTH = 'REMOVE_AUTH'


export const GET_OTP_REQUEST ='GET_OTP_REQUEST'
export const GET_OTP_SUCCESS ='GET_OTP_SUCCESS'
export const GET_OTP_FAILED ='GET_OTP_FAILED'

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const CHANGE_PASS_REQUEST = 'CHANGE_PASS_REQUEST'
export const CHANGE_PASS_SUCCESS = 'CHANGE_PASS_SUCCESS'
export const CHANGE_PASS_FAILED =  'CHANGE_PASS_FAILED'

export const GET_USER_DATA_REQUEST = 'GET_USER_DATA_REQUEST'
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS'
export const GET_USER_DATA_FAILED = 'GET_USER_DATA_FAILED'